server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317" # Matches the collector gRPC port

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    path: /etc/tempo/traces

ingester:
  trace_idle_period: 10s
  max_block_bytes: 5000000
  max_block_duration: 5m

overrides:
  per_tenant_override_config: {}
